### ISSUE TITLE
Server returns what the awesome client sent.... make it TCPier !!

### ISSUE THREAD

**Issue by BenChemouny** [BenChemouny/StudioWorld#1]
Now the server works only in UDP, fix it quickly , SirSch

**Comment by NadavSch** [comment]
@BenChemouny Fixed, learn to tag.

**Comment by BenChemouny** [comment]
Great job, Employee of the Year

**Comment by NadavSch** [comment]
@BenChemouny 
Now about my raise...

**Comment by BenChemouny** [comment]
https://www.google.co.il/imgres?imgurl=https://s-media-cache-ak0.pinimg.com/736x/79/ba/1b/79ba1bbd21ccc21eb6b32b5e60e31340.jpg&imgrefurl=https://www.pinterest.com/pin/429953095654272596/&h=530&w=376&tbnid=X5u7wKlnLXJhTM:&docid=vdoIQcoGjvnwZM&ei=JYF5VqjlJ4X2PbyirZAE&tbm=isch&ved=0ahUKEwjoi4OX-O_JAhUFew8KHTxRC0IQMwg9KA0wDQ
